// bossConfig.js
export const bossConfig = {
  "Arachir the Ancient One": { minDays: 6, maxDays: 9, zone: 'PACC' },
  "Barbaria": { minDays: 8, maxDays: 13, zone: 'PACC' },
  "Battlemaster Zunzu(East)": { minDays: 6, maxDays: 9, zone: 'PACC' },
  "Battlemaster Zunzu(West)": { minDays: 6, maxDays: 9, zone: 'PACC' },
  "Big Boss Trolliver": { minDays: 3, maxDays: 8, zone: 'PACC' },
  "Captain Jones": { minDays: 6, maxDays: 10, zone: 'PACC' },
  "Countess Sorrow": { minDays: 14, maxDays: 21, zone: 'PACC' },
  "Cublarc the Plunderer(Surface)": { minDays: 6, maxDays: 9, zone: 'PACC' },
  "Dharalion": { minDays: 6, maxDays: 8, zone: 'FACC' },
  "Diblis the Fair": { minDays: 10, maxDays: 16, zone: 'PACC' },
  "Dracola": { minDays: 14, maxDays: 21, zone: 'PACC' },
  "Dreadmaw(East)": { minDays: 1, maxDays: 17, zone: 'PACC' },
  "Dreadmaw(West)": { minDays: 1, maxDays: 17, zone: 'PACC' },
  "Flamecaller Zazrak(Surface)": { minDays: 5, maxDays: 10, zone: 'PACC' },
  "Flamecaller Zazrak(Mountain)": { minDays: 5, maxDays: 10, zone: 'PACC' },
  "Fleabringer(NW)": { minDays: 5, maxDays: 31, zone: 'PACC' },
  "Fleabringer(SW)": { minDays: 5, maxDays: 31, zone: 'PACC' },
  "Fleabringer(Surface)": { minDays: 5, maxDays: 31, zone: 'PACC' },
  "Foreman Kneebiter": { minDays: 3, maxDays: 8, zone: 'FACC' },
  "General Murius": { minDays: 6, maxDays: 9, zone: 'FACC' },
  "Grandfather Tridian": { minDays: 6, maxDays: 9, zone: 'PACC' },
  "Gravelord Oshuran": { minDays: 7, maxDays: 12, zone: 'PACC' },
  "Grorlam": { minDays: 3, maxDays: 8 , zone: 'FACC'},
  "Hairman the Huge": { minDays: 5, maxDays: 10, zone: 'PACC' },
  "Hatebreeder": { minDays: 6, maxDays: 9, zone: 'PACC' },
  "High Templar Cobrass": { minDays: 6, maxDays: 9, zone: 'PACC' },
  "Hirintror(Mines)": { minDays: 10, maxDays: 30, zone: 'PACC' },
  "Hirintror(Nibelor)": { minDays: 10, maxDays: 30, zone: 'PACC' },
  "Man in the Cave": { minDays: 12, maxDays: 16, zone: 'PACC' },
  "Massacre": { minDays: 14, maxDays: 21, zone: 'PACC' },
  "Mr. Punish": { minDays: 14, maxDays: 21, zone: 'PACC' },
  "Ocyakao": { minDays: 16, maxDays: 26, zone: 'PACC' },
  "Omrafir": { minDays: 14, maxDays: 28, zone: 'PACC' },
  "Rotworm Queen(Darashia)": { minDays: 12, maxDays: 16, zone: 'PACC' },
  "Rotworm Queen(Edron)": { minDays: 12, maxDays: 16, zone: 'PACC' },
  "Rotworm Queen(Hellgate)": { minDays: 12, maxDays: 16, zone: 'PACC' },
  "Rotworm Queen(Liberty Bay)": { minDays: 12, maxDays: 16, zone: 'PACC' },
  "Rukor Zad": { minDays: 6, maxDays: 9, zone: 'FACC' },
  "Shlorg": { minDays: 13, maxDays: 29, zone: 'PACC' },
  "Sir Valorcrest": { minDays: 5, maxDays: 9, zone: 'PACC' },
  "Smuggler Baron Silvertoe": { minDays: 8, maxDays: 16, zone: 'PACC' },
  "The Big Bad One": { minDays: 6, maxDays: 11, zone: 'PACC' },
  "The Evil Eye": { minDays: 6, maxDays: 12, zone: 'FACC' },
  "The Frog Prince": { minDays: 12, maxDays: 19, zone: 'FACC' },
  "The Handmaiden": { minDays: 14, maxDays: 21, zone: 'PACC' },
  "The Imperor": { minDays: 14, maxDays: 21, zone: 'PACC' },
  "The Old Whopper": { minDays: 5, maxDays: 11, zone: 'PACC' },
  "The Plasmother": { minDays: 14, maxDays: 21, zone: 'PACC' },
  "The Voice Of Ruin(Middle)": { minDays: 6, maxDays: 17, zone: 'PACC' },
  "The Voice Of Ruin(Ghastly)": { minDays: 6, maxDays: 17, zone: 'PACC' },
  "The Welter": { minDays: 16, maxDays: 29, zone: 'PACC' },
  "Tyrn(Darashia)": { minDays: 12, maxDays: 25, zone: 'PACC' },
  "Tyrn(Liberty Bay)": { minDays: 12, maxDays: 25, zone: 'PACC' },
  "Tzumrah The Dazzler": { minDays: 20, maxDays: 28, zone: 'PACC' },
  "Warlord Ruzad": { minDays: 6, maxDays: 9, zone: 'FACC' },
  "White Pale(Darashia)": { minDays: 17, maxDays: 37, zone: 'PACC' },
  "White Pale(Edron)": { minDays: 17, maxDays: 37, zone: 'PACC' },
  "White Pale(Liberty Bay)": { minDays: 17, maxDays: 37, zone: 'PACC' },
  "Xenia": { minDays: 7, maxDays: 14, zone: 'FACC' },
  "Yaga the Crone": { minDays: 5, maxDays: 7, zone: 'FACC' },
  "Zarabustor": { minDays: 6, maxDays: 9, zone: 'FACC' },
  "Zevelon Duskbringer": { minDays: 6, maxDays: 10 },
  "Zushuka": { minDays: 19, maxDays: 29, zone: 'PACC' },
  "midnight panthers": { minDays: 2, maxDays: 4, zone: 'PACC' },
  "Yeti": { minDays: 16, maxDays: 30, zone: 'PACC' },
};

export const raidsConfig = {
  "Cublarc the Plunderer(Horde)": { minDays: 5, maxDays: 10 },
  "Ferumbras": { minDays: 161, maxDays: 175 },
  "Gaz'haragoth": { minDays: 14, maxDays: 28 },
  "Ghazbaran": { minDays: 161, maxDays: 175 },
  "Grand Mother Foulscale": { minDays: 5, maxDays: 10 },
  "Morgaroth": { minDays: 168, maxDays: 175 },
  "Morshabaal": { minDays: 154, maxDays: 175 },
  "Orshabaal": { minDays: 154, maxDays: 175 },
  "The Abomination": { minDays: 155, maxDays: 174 },
  "The Blightfather": { minDays: 5, maxDays: 10 },
  "The Pale Count": { minDays: 16, maxDays: 30 },
  "Willi Wasp": { minDays: 5, maxDays: 10 },
  "Zomba": { minDays: 3, maxDays: 9 },
  "Zulazza the Corruptor": { minDays: 7, maxDays: 20 },
  "Chizzoron the Distorter": { minDays: 7, maxDays: 20 },
  "Cublarc the Plunderer(Zzaion)": { minDays: 7, maxDays: 20 }
};