// bossNames.js
export function getAllBossNames() {
    return [
      "Arachir the Ancient One",
      "Arthom The Hunter",
      "Bane Lord",
      "Barbaria",
      "Battlemaster Zunzu",
      "Big Boss Trolliver",
      "Burster",
      "Captain Jones",
      "Chizzoron the Distorter",
      "Countess Sorrow",
      "Cublarc the Plunderer",
      "Devovorga",
      "Dharalion",
      "Diblis the Fair",
      "Dracola",
      "Dreadful Disruptor",
      "Dreadmaw",
      "Elvira Hammerthrust",
      "Feroxa",
      "Ferumbras",
      "Flamecaller Zazrak",
      "Fleabringer",
      "Foreman Kneebiter",
      "Furyosa",
      "Gaz'haragoth",
      "General Murius",
      "Ghazbaran",
      "Grand Mother Foulscale",
      "Grandfather Tridian",
      "Gravelord Oshuran",
      "Groam",
      "Grorlam",
      "Hairman the Huge",
      "Hatebreeder",
      "High Templar Cobrass",
      "Hirintror",
      "Jesse the Wicked",
      "Mahatheb",
      "Man in the Cave",
      "Massacre",
      "Morgaroth",
      "Mornenion",
      "Morshabaal",
      "midnight panthers",
      "Mr. Punish",
      "Ocyakao",
      "Omrafir",
      "Oodok Witchmaster",
      "Orshabaal",
      "Robby the Reckless",
      "Rotrender",
      "Rotworm Queen",
      "Rukor Zad",
      "Shlorg",
      "Sir Valorcrest",
      "Smuggler Baron Silvertoe",
      "The Abomination",
      "The Big Bad One",
      "The Blightfather",
      "The Evil Eye",
      "The Frog Prince",
      "The Handmaiden",
      "The Hungerer",
      "The Imperor",
      "The Manhunter",
      "The Mean Masher",
      "The Mutated Pumpkin",
      "The Old Whopper",
      "The Pale Count",
      "The Plasmother",
      "The Voice Of Ruin",
      "The Welter",
      "Tyrn",
      "Tzumrah The Dazzler",
      "Warlord Ruzad",
      "White Pale",
      "Willi Wasp",
      "Xenia",
      "Yaga the Crone",
      "Yakchal",
      "Zarabustor",
      "Zevelon Duskbringer",
      "Zomba",
      "Zulazza the Corruptor",
      "Zushuka"
    ];
  }
  